server.port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb?characterEncoding=UTF-8&useUnicode=true
    username: root
    password: 123456
  redis:
    host: localhost
    password: 123456
    database: 1
    timeout: 5s
logging:
  file: "log/my.log"
  file.max-history: 10
  file.max-size: 10MB
  level:
    root: info
    dr uid.sql.Statement: debug
test:
  array:
    - host: 1
      port: 2
    - host: 2
      port: 2
